#  ___ _ _      _   _    ___         _           _
# | __| (_)__ _| |_| |_ / __|___ _ _| |_ _ _ ___| |
# | _|| | / _` | ' \  _| (__/ _ \ ' \  _| '_/ _ \ |
# |_| |_|_\__, |_||_\__|\___\___/_||_\__|_| \___/_|
#         |___/
# Doar: https://geofang.com/donate
# Discord: https://geofang.com/discord
# Página Spigot: https://www.spigotmc.org/resources/flightcontrol.55168/

settings:
  # Atualiza a configuração automaticamente e adiciona novos recursos
  auto_update: true
  # Recarrega automaticamente a configuração quando as alterações são salvas
  auto_reload: true
  # Permite que o comando /fly seja alterado para outro nome de comando (ex: /votefly)
  fly_command_name: "fly"
  # Habilita o voo automaticamente (sem necessidade de comando)
  auto_enable_flight: true
  # A velocidade padrão é 1.0 e corresponde aos valores do /flyspeed do Essentials (0-10)
  flight_speed: 1.0
  # A velocidade máxima de voo que um usuário pode definir usando /flyspeed (não pode ser maior que 10)
  max_flight_speed: 1.0
  # Desabilita o voo acima do limite de altura de blocos
  height_limit: -1
  # Suporta: CombatLogX, DeluxeCombat
  # NOTA: desabilite o desligamento/habilitação de voo na configuração do plugin de combate para evitar problemas
  disable_flight_in_combat: false
  # Previne dano de queda quando o voo é desabilitado no ar pelo FlightControl
  prevent_fall_damage: false
  # Suporta: EssentialsX, PremiumVanish, SuperVanish
  # Previne desabilitação do voo enquanto estiver invisível
  vanish_bypass: true

tempfly:
  # O tempfly deve diminuir mesmo quando o jogador não está voando?
  always_decrease: true

# NOTA: este recurso é intensivo em recursos e pode causar problemas de desempenho
nearby_disable:
  # Desabilita o voo quando um jogador está dentro de um certo alcance de blocos (defina como -1 para desabilitar)
  range: -1
  # Suporta: FactionsUUID
  # Faz a configuração "range" funcionar apenas para inimigos de facção
  factions_enemy: true

trail:
  enabled: false
  # Informações de Partículas 1.8: https://geofang.com/flightcontrol/particles/1
  # Informações de Partículas 1.15: https://geofang.com/flightcontrol/particles/2
  particle: "CLOUD"
  amount: 2
  # Por favor, veja os links de informações de partículas acima para saber quais partículas podem mudar de cor
  # Seletor de cor (RGB): https://www.google.com/search?q=color+picker
  rgb: "0,0,0"

sounds:
  # Toca os sons a CADA duplo toque na barra de espaço
  every_enable: false
  every_disable: false
  # Por favor, use os nomes de som da coluna "Sound Event"
  # Lista 1.8: https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values_before_1.9
  # Lista Atual (1.21): https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values
  enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  disable:
    sound: "NONE"
    pitch: 1
    volume: 1
  # "can_enable" e "cannot_enable" são usados quando "auto_enable" é false
  # ou se o jogador desabilita seu próprio voo com /fly
  can_enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  cannot_enable:
    sound: "NONE"
    pitch: 1
    volume: 1